artifacts/Dockerfile
Reverts mosip/artifactory-ref-impl#25
=> Revert "Enabled Docker user"

artifacts/Dockerfile
resolved path not found error while creating zip and added JRE for reg client.
=> resolved path not found error while creating zip.

artifacts/Dockerfile
=> [DSD-73] Updated kernel-ref-idobjectvalidator

artifacts/src/i18n/admin-i18n-bundle/i18n/ara.json, artifacts/src/i18n/admin-i18n-bundle/i18n/eng.json, artifacts/src/i18n/admin-i18n-bundle/i18n/fra.json, artifacts/src/i18n/admin-i18n-bundle/i18n/hin.json, artifacts/src/i18n/admin-i18n-bundle/i18n/kan.json, artifacts/src/i18n/admin-i18n-bundle/i18n/tam.json
as per @aranaravi  made the changes.
Arabic file is copy and replaced
=> Updated the resource bundle for admin fix

artifacts/src/i18n/admin-i18n-bundle/i18n/ara.json, artifacts/src/i18n/admin-i18n-bundle/i18n/default.json, artifacts/src/i18n/admin-i18n-bundle/i18n/eng.json, artifacts/src/i18n/admin-i18n-bundle/i18n/fra.json, artifacts/src/i18n/admin-i18n-bundle/i18n/hin.json, artifacts/src/i18n/admin-i18n-bundle/i18n/kan.json, artifacts/src/i18n/admin-i18n-bundle/i18n/tam.json
Aravindh shared the files for the changes made
=> Changes for pop-up message

artifacts/Dockerfile, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/auth-partner.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/auth-policy.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/data-share-policy.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/device-detail.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/device-partner.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/ftm-detail.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/ftm-partner.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/misp-partner.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/misp.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/partner.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/pmanager.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/policy-group.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/policy-mapping.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/sbi-detail.json, artifacts/src/i18n/pmp-i18n-bundle/i18n/ara.json, artifacts/src/i18n/pmp-i18n-bundle/i18n/eng.json, artifacts/src/i18n/pmp-i18n-bundle/i18n/fra.json, artifacts/src/i18n/pmp-i18n-bundle/i18n/hin.json, artifacts/src/i18n/pmp-i18n-bundle/i18n/kan.json, artifacts/src/i18n/pmp-i18n-bundle/i18n/tam.json
Added resource bundle for PMP.
=> Added resource bundle for PMP.

artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/auth-policy.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/data-share-policy.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/device-detail.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/ftm-detail.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/partner.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/policy-group.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/policy-mapping.json, artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/sbi-detail.json, artifacts/src/i18n/pmp-i18n-bundle/i18n/ara.json, artifacts/src/i18n/pmp-i18n-bundle/i18n/eng.json, artifacts/src/i18n/pmp-i18n-bundle/i18n/fra.json, artifacts/src/i18n/pmp-i18n-bundle/i18n/hin.json, artifacts/src/i18n/pmp-i18n-bundle/i18n/kan.json, artifacts/src/i18n/pmp-i18n-bundle/i18n/tam.json
https://mosip.atlassian.net/browse/MOSIP-19414
=> Changes related to label in filter popup

artifacts/release.sh, artifacts/snapshot.sh
To download the SDK jar along with its dependency jars
=> [ MOSIP-24438 ] updated snapshot.sh & release.sh

artifacts/release.sh, artifacts/snapshot.sh
Reverts mosip/artifactory-ref-impl#365
=> Revert "[ MOSIP-24438 ] updated snapshot.sh & release.sh"

artifacts/release.sh, artifacts/snapshot.sh
to download sdk jar along with its dependency jars
=> [ MOSIP-24438 ] updated release.sh & snapshot.sh

artifacts/src/i18n/idp-i18n-bundle/ar.json, artifacts/src/i18n/idp-i18n-bundle/ara.json, artifacts/src/i18n/idp-i18n-bundle/en.json, artifacts/src/i18n/idp-i18n-bundle/eng.json, artifacts/src/i18n/idp-i18n-bundle/hi.json, artifacts/src/i18n/idp-i18n-bundle/hin.json, artifacts/src/i18n/idp-i18n-bundle/kan.json, artifacts/src/i18n/idp-i18n-bundle/kn.json, artifacts/src/i18n/idp-i18n-bundle/ta.json, artifacts/src/i18n/idp-i18n-bundle/tam.json
[MOSIP-25031](https://mosip.atlassian.net/browse/MOSIP-25031)
=> IDP-UI translation for qrcode component added

artifacts/Dockerfile
Reverts mosip/artifactory-ref-impl#377
=> Revert "Update Dockerfile"

artifacts/src/i18n/idp-i18n-bundle/ar.json, artifacts/src/i18n/idp-i18n-bundle/ara.json, artifacts/src/i18n/idp-i18n-bundle/en.json, artifacts/src/i18n/idp-i18n-bundle/eng.json, artifacts/src/i18n/idp-i18n-bundle/hi.json, artifacts/src/i18n/idp-i18n-bundle/hin.json, artifacts/src/i18n/idp-i18n-bundle/kan.json, artifacts/src/i18n/idp-i18n-bundle/kn.json, artifacts/src/i18n/idp-i18n-bundle/ta.json, artifacts/src/i18n/idp-i18n-bundle/tam.json
Changes suggested
IDPQRCode changes to LoginQRCode
registration with e-signet removed
=> PR corrections

artifacts/configure.sh
commented the removal of bio-sdk-client folder.
=> Debug check

artifacts/configure.sh
Reverts mosip/artifactory-ref-impl#438
=> Revert "Debug check"

artifacts/pom.xml
Reverts mosip/artifactory-ref-impl#477
=> Revert "Added new esignet integration libraries"

artifacts/src/i18n/pmp-entity-spec-bundle/entity-spec/sbi-detail.json
Reverts mosip/artifactory-ref-impl#483
=> Revert "Release 1.2.0.1"

.github/workflows/push-trigger.yml
[MOSIP-25631]
[MOSIP-25631]: https://mosip.atlassian.net/browse/MOSIP-25631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOSIP-29135] Updated workflows with reusable templates

artifacts/pom.xml
Reverts mosip/artifactory-ref-impl#532
=> Revert "MOSIP-28694"

artifacts/pom.xml
Reverts mosip/artifactory-ref-impl#530
=> Revert "[MOSIP-28694] added for consent release"

artifacts/pom.xml
Reverts mosip/artifactory-ref-impl#543
=> Revert "Esignet consent 1.1.0 release change"

artifacts/pom.xml, artifacts/src/i18n/esignet-i18n-bundle/ar.json, artifacts/src/i18n/esignet-i18n-bundle/en.json, artifacts/src/i18n/esignet-i18n-bundle/hi.json, artifacts/src/i18n/esignet-i18n-bundle/kn.json, artifacts/src/i18n/esignet-i18n-bundle/ta.json
Reverts mosip/artifactory-ref-impl#542
=> Revert "missing inji label added for 1.1.0 support"

artifacts/src/i18n/esignet-i18n-bundle/km.json
Reverted back the changes made
=> [ES-393]Update km.json

artifacts/src/i18n/esignet-i18n-bundle/en.json
Reverted back the changes made.
=> [ES-393]Update en.json

artifacts/src/i18n/esignet-i18n-bundle/default.json
Reverts mosip/artifactory-ref-impl#630
=> Revert "[ES-393] khmer only language for esignet"

artifacts/src/i18n/esignet-i18n-bundle/km.json
1. `esignet_details_heading` key is missing from khmer language
2. `Form` key has been added up in khmer language
=> [ES-393] esignet_details_heading key is missing, added Form key in khmer

artifacts/pom.xml
Reverts mosip/artifactory-ref-impl#671
=> Revert "[DSD-4731]Update pom.xml"

artifacts/pom.xml
=> [DSD-5182] Updated kernel-smsserviceprovider-msg91-1.2.1-java21.jar in pom.xml

artifacts/src/theme/esignet-signup-theme/variables.css
Sync from: https://github.com/mosip/artifactory-ref-impl/pull/743
=> Sync release theme to common name

.github/workflows/push-trigger.yml
=> Adding ES branch to push trigger

artifacts/src/theme/esignet-signup-theme/variables.css
Added css variable for Kyc provider, Terms & Condn and Video Preview
=> [ES-1381] added var for kyc, tnc & video preview

artifacts/pom.xml
[MOSIP-35396] Added dependencies required for the Java 21 beta release in artifactory.
[MOSIP-35396]: https://mosip.atlassian.net/browse/MOSIP-35396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOSIP-35396] Added dependencies required for the Java 21 beta release in artifactory.

artifacts/Dockerfile, artifacts/configure.sh, artifacts/pom.xml
Reverts mosip/artifactory-ref-impl#947Revert "[MOSIP-35396] Added dependencies required for the Java 21 beta release in artifactory."
[MOSIP-35396]: https://mosip.atlassian.net/browse/MOSIP-35396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "[MOSIP-35396] Added dependencies required for the Java 21 beta release in artifactory."

artifacts/Dockerfile, artifacts/pom.xml
Revert "[MOSIP-35396] Added dependencies required for the Java 21 beta release in artifactory." 
[MOSIP-35396]: https://mosip.atlassian.net/browse/MOSIP-35396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "[MOSIP-35396] Added dependencies required for the Java 21 beta release in artifactory." 

artifacts/pom.xml
[MOSIP-36413] Removed childauthfilter from pom.xml
[MOSIP-36413]: https://mosip.atlassian.net/browse/MOSIP-36413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOSIP-36413] Removed childauthfilter from pom.xml

artifacts/src/i18n/esignet-signup-i18n-bundle/en.json
Reverts mosip/artifactory-ref-impl#979
=> Revert "[ES-1115] modified Terms & Conditions"

artifacts/src/i18n/esignet-signup-i18n-bundle/en.json
[ES-983] Updated video preview instructions
[ES-983]: https://mosip.atlassian.net/browse/ES-983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ES-983] Updated video preview instructions

artifacts/src/i18n/esignet-signup-i18n-bundle/en.json
displaying complete condition to create a valid password.
=> [ES-1560]changed the i icon message for password field

artifacts/src/i18n/esignet-signup-i18n-bundle/default.json
Language is configured to have single language (Khmer) both in eSignet & Signup portal
=> [ES-1132] config changes for english language(reverting-back)

artifacts/pom.xml
Reverts mosip/artifactory-ref-impl#1050
=> Revert "Update pom.xml"
